// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package Service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ModuleId int32

const (
	// 请求登陆
	ModuleId_LoginReq  ModuleId = 0
	ModuleId_LoginResp ModuleId = 1
	// 请求注册
	ModuleId_RegisterReq  ModuleId = 2
	ModuleId_RegisterResp ModuleId = 3
	// 请求获得玩家的信息
	ModuleId_PlayerInfoReq  ModuleId = 4
	ModuleId_PlayerInfoResp ModuleId = 5
	// 请求获得theirturn
	ModuleId_TheirturnReq  ModuleId = 6
	ModuleId_TheirturnResp ModuleId = 7
	// 请求获得pending
	ModuleId_PendingReq  ModuleId = 8
	ModuleId_PendingResp ModuleId = 9
	// 请求获得myturn
	ModuleId_MyturnReq  ModuleId = 10
	ModuleId_MyturnResp ModuleId = 11
	// 请求获得对战的history
	ModuleId_MyHistoryReq  ModuleId = 14
	ModuleId_MyHistoryResp ModuleId = 15
	// 请求获得收藏的history
	ModuleId_MyCollectedHistoryReq  ModuleId = 16
	ModuleId_MyCollectedHistoryResp ModuleId = 17
	// 获取头像
	ModuleId_AvatarReq  ModuleId = 18
	ModuleId_AvatarResp ModuleId = 19
	// ai下棋
	ModuleId_Ainewgamereq  ModuleId = 20
	ModuleId_Playerstep    ModuleId = 21
	ModuleId_Aistep        ModuleId = 22
	ModuleId_Aioldgameresp ModuleId = 23
)

var ModuleId_name = map[int32]string{
	0:  "LoginReq",
	1:  "LoginResp",
	2:  "RegisterReq",
	3:  "RegisterResp",
	4:  "PlayerInfoReq",
	5:  "PlayerInfoResp",
	6:  "TheirturnReq",
	7:  "TheirturnResp",
	8:  "PendingReq",
	9:  "PendingResp",
	10: "MyturnReq",
	11: "MyturnResp",
	14: "MyHistoryReq",
	15: "MyHistoryResp",
	16: "MyCollectedHistoryReq",
	17: "MyCollectedHistoryResp",
	18: "AvatarReq",
	19: "AvatarResp",
	20: "Ainewgamereq",
	21: "Playerstep",
	22: "Aistep",
	23: "Aioldgameresp",
}
var ModuleId_value = map[string]int32{
	"LoginReq":               0,
	"LoginResp":              1,
	"RegisterReq":            2,
	"RegisterResp":           3,
	"PlayerInfoReq":          4,
	"PlayerInfoResp":         5,
	"TheirturnReq":           6,
	"TheirturnResp":          7,
	"PendingReq":             8,
	"PendingResp":            9,
	"MyturnReq":              10,
	"MyturnResp":             11,
	"MyHistoryReq":           14,
	"MyHistoryResp":          15,
	"MyCollectedHistoryReq":  16,
	"MyCollectedHistoryResp": 17,
	"AvatarReq":              18,
	"AvatarResp":             19,
	"Ainewgamereq":           20,
	"Playerstep":             21,
	"Aistep":                 22,
	"Aioldgameresp":          23,
}

func (x ModuleId) String() string {
	return proto.EnumName(ModuleId_name, int32(x))
}
func (ModuleId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0}
}

type Player_LoginResp_LoginResult int32

const (
	Player_LoginResp_Login_Success                Player_LoginResp_LoginResult = 0
	Player_LoginResp_Login_Failure                Player_LoginResp_LoginResult = 1
	Player_LoginResp_Login_WrongPasswordOrAccount Player_LoginResp_LoginResult = 2
	Player_LoginResp_Login_NonexistentAccount     Player_LoginResp_LoginResult = 3
)

var Player_LoginResp_LoginResult_name = map[int32]string{
	0: "Login_Success",
	1: "Login_Failure",
	2: "Login_WrongPasswordOrAccount",
	3: "Login_NonexistentAccount",
}
var Player_LoginResp_LoginResult_value = map[string]int32{
	"Login_Success":                0,
	"Login_Failure":                1,
	"Login_WrongPasswordOrAccount": 2,
	"Login_NonexistentAccount":     3,
}

func (x Player_LoginResp_LoginResult) String() string {
	return proto.EnumName(Player_LoginResp_LoginResult_name, int32(x))
}
func (Player_LoginResp_LoginResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 1, 0}
}

type Player_RegisterResp_RegisterResult int32

const (
	Player_RegisterResp_Register_Success   Player_RegisterResp_RegisterResult = 0
	Player_RegisterResp_Register_Failure   Player_RegisterResp_RegisterResult = 1
	Player_RegisterResp_Register_Duplicate Player_RegisterResp_RegisterResult = 2
)

var Player_RegisterResp_RegisterResult_name = map[int32]string{
	0: "Register_Success",
	1: "Register_Failure",
	2: "Register_Duplicate",
}
var Player_RegisterResp_RegisterResult_value = map[string]int32{
	"Register_Success":   0,
	"Register_Failure":   1,
	"Register_Duplicate": 2,
}

func (x Player_RegisterResp_RegisterResult) String() string {
	return proto.EnumName(Player_RegisterResp_RegisterResult_name, int32(x))
}
func (Player_RegisterResp_RegisterResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 3, 0}
}

type Player struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0}
}
func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (dst *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(dst, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

// 登陆请求
type Player_LoginReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=passWord,proto3" json:"passWord,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player_LoginReq) Reset()         { *m = Player_LoginReq{} }
func (m *Player_LoginReq) String() string { return proto.CompactTextString(m) }
func (*Player_LoginReq) ProtoMessage()    {}
func (*Player_LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 0}
}
func (m *Player_LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_LoginReq.Unmarshal(m, b)
}
func (m *Player_LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_LoginReq.Marshal(b, m, deterministic)
}
func (dst *Player_LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_LoginReq.Merge(dst, src)
}
func (m *Player_LoginReq) XXX_Size() int {
	return xxx_messageInfo_Player_LoginReq.Size(m)
}
func (m *Player_LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_Player_LoginReq proto.InternalMessageInfo

func (m *Player_LoginReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Player_LoginReq) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

// 登陆结果
type Player_LoginResp struct {
	Result               Player_LoginResp_LoginResult `protobuf:"varint,1,opt,name=result,proto3,enum=Module.Player_LoginResp_LoginResult" json:"result,omitempty"`
	Id                   string                       `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *Player_LoginResp) Reset()         { *m = Player_LoginResp{} }
func (m *Player_LoginResp) String() string { return proto.CompactTextString(m) }
func (*Player_LoginResp) ProtoMessage()    {}
func (*Player_LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 1}
}
func (m *Player_LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_LoginResp.Unmarshal(m, b)
}
func (m *Player_LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_LoginResp.Marshal(b, m, deterministic)
}
func (dst *Player_LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_LoginResp.Merge(dst, src)
}
func (m *Player_LoginResp) XXX_Size() int {
	return xxx_messageInfo_Player_LoginResp.Size(m)
}
func (m *Player_LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_Player_LoginResp proto.InternalMessageInfo

func (m *Player_LoginResp) GetResult() Player_LoginResp_LoginResult {
	if m != nil {
		return m.Result
	}
	return Player_LoginResp_Login_Success
}

func (m *Player_LoginResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// 注册请求
type Player_RegisterReq struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	PassWord             string   `protobuf:"bytes,2,opt,name=passWord,proto3" json:"passWord,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player_RegisterReq) Reset()         { *m = Player_RegisterReq{} }
func (m *Player_RegisterReq) String() string { return proto.CompactTextString(m) }
func (*Player_RegisterReq) ProtoMessage()    {}
func (*Player_RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 2}
}
func (m *Player_RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_RegisterReq.Unmarshal(m, b)
}
func (m *Player_RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_RegisterReq.Marshal(b, m, deterministic)
}
func (dst *Player_RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_RegisterReq.Merge(dst, src)
}
func (m *Player_RegisterReq) XXX_Size() int {
	return xxx_messageInfo_Player_RegisterReq.Size(m)
}
func (m *Player_RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_Player_RegisterReq proto.InternalMessageInfo

func (m *Player_RegisterReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Player_RegisterReq) GetPassWord() string {
	if m != nil {
		return m.PassWord
	}
	return ""
}

// 注册结果
type Player_RegisterResp struct {
	Result               Player_RegisterResp_RegisterResult `protobuf:"varint,1,opt,name=result,proto3,enum=Module.Player_RegisterResp_RegisterResult" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *Player_RegisterResp) Reset()         { *m = Player_RegisterResp{} }
func (m *Player_RegisterResp) String() string { return proto.CompactTextString(m) }
func (*Player_RegisterResp) ProtoMessage()    {}
func (*Player_RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 3}
}
func (m *Player_RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_RegisterResp.Unmarshal(m, b)
}
func (m *Player_RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_RegisterResp.Marshal(b, m, deterministic)
}
func (dst *Player_RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_RegisterResp.Merge(dst, src)
}
func (m *Player_RegisterResp) XXX_Size() int {
	return xxx_messageInfo_Player_RegisterResp.Size(m)
}
func (m *Player_RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_Player_RegisterResp proto.InternalMessageInfo

func (m *Player_RegisterResp) GetResult() Player_RegisterResp_RegisterResult {
	if m != nil {
		return m.Result
	}
	return Player_RegisterResp_Register_Success
}

// 请求玩家信息请求
type Player_PlayerInfoReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player_PlayerInfoReq) Reset()         { *m = Player_PlayerInfoReq{} }
func (m *Player_PlayerInfoReq) String() string { return proto.CompactTextString(m) }
func (*Player_PlayerInfoReq) ProtoMessage()    {}
func (*Player_PlayerInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 4}
}
func (m *Player_PlayerInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_PlayerInfoReq.Unmarshal(m, b)
}
func (m *Player_PlayerInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_PlayerInfoReq.Marshal(b, m, deterministic)
}
func (dst *Player_PlayerInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_PlayerInfoReq.Merge(dst, src)
}
func (m *Player_PlayerInfoReq) XXX_Size() int {
	return xxx_messageInfo_Player_PlayerInfoReq.Size(m)
}
func (m *Player_PlayerInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_PlayerInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_Player_PlayerInfoReq proto.InternalMessageInfo

func (m *Player_PlayerInfoReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// 请求玩家信息结果
type Player_PlayerInfoResp struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Avataredge           string   `protobuf:"bytes,3,opt,name=avataredge,proto3" json:"avataredge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player_PlayerInfoResp) Reset()         { *m = Player_PlayerInfoResp{} }
func (m *Player_PlayerInfoResp) String() string { return proto.CompactTextString(m) }
func (*Player_PlayerInfoResp) ProtoMessage()    {}
func (*Player_PlayerInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 5}
}
func (m *Player_PlayerInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_PlayerInfoResp.Unmarshal(m, b)
}
func (m *Player_PlayerInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_PlayerInfoResp.Marshal(b, m, deterministic)
}
func (dst *Player_PlayerInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_PlayerInfoResp.Merge(dst, src)
}
func (m *Player_PlayerInfoResp) XXX_Size() int {
	return xxx_messageInfo_Player_PlayerInfoResp.Size(m)
}
func (m *Player_PlayerInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_PlayerInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_Player_PlayerInfoResp proto.InternalMessageInfo

func (m *Player_PlayerInfoResp) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Player_PlayerInfoResp) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Player_PlayerInfoResp) GetAvataredge() string {
	if m != nil {
		return m.Avataredge
	}
	return ""
}

// 请求theirturn
type Player_TheirturnReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player_TheirturnReq) Reset()         { *m = Player_TheirturnReq{} }
func (m *Player_TheirturnReq) String() string { return proto.CompactTextString(m) }
func (*Player_TheirturnReq) ProtoMessage()    {}
func (*Player_TheirturnReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 6}
}
func (m *Player_TheirturnReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_TheirturnReq.Unmarshal(m, b)
}
func (m *Player_TheirturnReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_TheirturnReq.Marshal(b, m, deterministic)
}
func (dst *Player_TheirturnReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_TheirturnReq.Merge(dst, src)
}
func (m *Player_TheirturnReq) XXX_Size() int {
	return xxx_messageInfo_Player_TheirturnReq.Size(m)
}
func (m *Player_TheirturnReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_TheirturnReq.DiscardUnknown(m)
}

var xxx_messageInfo_Player_TheirturnReq proto.InternalMessageInfo

func (m *Player_TheirturnReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// 请求获得theirturn结果
type Player_TheirturnResp struct {
	Theirturn            []*PlayerGameUnderway `protobuf:"bytes,1,rep,name=theirturn,proto3" json:"theirturn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Player_TheirturnResp) Reset()         { *m = Player_TheirturnResp{} }
func (m *Player_TheirturnResp) String() string { return proto.CompactTextString(m) }
func (*Player_TheirturnResp) ProtoMessage()    {}
func (*Player_TheirturnResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 7}
}
func (m *Player_TheirturnResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_TheirturnResp.Unmarshal(m, b)
}
func (m *Player_TheirturnResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_TheirturnResp.Marshal(b, m, deterministic)
}
func (dst *Player_TheirturnResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_TheirturnResp.Merge(dst, src)
}
func (m *Player_TheirturnResp) XXX_Size() int {
	return xxx_messageInfo_Player_TheirturnResp.Size(m)
}
func (m *Player_TheirturnResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_TheirturnResp.DiscardUnknown(m)
}

var xxx_messageInfo_Player_TheirturnResp proto.InternalMessageInfo

func (m *Player_TheirturnResp) GetTheirturn() []*PlayerGameUnderway {
	if m != nil {
		return m.Theirturn
	}
	return nil
}

// 请求获得pending
type Player_PendingReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player_PendingReq) Reset()         { *m = Player_PendingReq{} }
func (m *Player_PendingReq) String() string { return proto.CompactTextString(m) }
func (*Player_PendingReq) ProtoMessage()    {}
func (*Player_PendingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 8}
}
func (m *Player_PendingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_PendingReq.Unmarshal(m, b)
}
func (m *Player_PendingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_PendingReq.Marshal(b, m, deterministic)
}
func (dst *Player_PendingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_PendingReq.Merge(dst, src)
}
func (m *Player_PendingReq) XXX_Size() int {
	return xxx_messageInfo_Player_PendingReq.Size(m)
}
func (m *Player_PendingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_PendingReq.DiscardUnknown(m)
}

var xxx_messageInfo_Player_PendingReq proto.InternalMessageInfo

func (m *Player_PendingReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// 请求获得pending结果
type Player_PendingResp struct {
	Pending              []*PlayerPending `protobuf:"bytes,1,rep,name=pending,proto3" json:"pending,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Player_PendingResp) Reset()         { *m = Player_PendingResp{} }
func (m *Player_PendingResp) String() string { return proto.CompactTextString(m) }
func (*Player_PendingResp) ProtoMessage()    {}
func (*Player_PendingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 9}
}
func (m *Player_PendingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_PendingResp.Unmarshal(m, b)
}
func (m *Player_PendingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_PendingResp.Marshal(b, m, deterministic)
}
func (dst *Player_PendingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_PendingResp.Merge(dst, src)
}
func (m *Player_PendingResp) XXX_Size() int {
	return xxx_messageInfo_Player_PendingResp.Size(m)
}
func (m *Player_PendingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_PendingResp.DiscardUnknown(m)
}

var xxx_messageInfo_Player_PendingResp proto.InternalMessageInfo

func (m *Player_PendingResp) GetPending() []*PlayerPending {
	if m != nil {
		return m.Pending
	}
	return nil
}

// 请求获得myturn
type Player_MyturnReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player_MyturnReq) Reset()         { *m = Player_MyturnReq{} }
func (m *Player_MyturnReq) String() string { return proto.CompactTextString(m) }
func (*Player_MyturnReq) ProtoMessage()    {}
func (*Player_MyturnReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 10}
}
func (m *Player_MyturnReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_MyturnReq.Unmarshal(m, b)
}
func (m *Player_MyturnReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_MyturnReq.Marshal(b, m, deterministic)
}
func (dst *Player_MyturnReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_MyturnReq.Merge(dst, src)
}
func (m *Player_MyturnReq) XXX_Size() int {
	return xxx_messageInfo_Player_MyturnReq.Size(m)
}
func (m *Player_MyturnReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_MyturnReq.DiscardUnknown(m)
}

var xxx_messageInfo_Player_MyturnReq proto.InternalMessageInfo

func (m *Player_MyturnReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// 请求获得myturn结果
type Player_MyturnResp struct {
	Myturn               []*PlayerGameUnderway `protobuf:"bytes,1,rep,name=myturn,proto3" json:"myturn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Player_MyturnResp) Reset()         { *m = Player_MyturnResp{} }
func (m *Player_MyturnResp) String() string { return proto.CompactTextString(m) }
func (*Player_MyturnResp) ProtoMessage()    {}
func (*Player_MyturnResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 11}
}
func (m *Player_MyturnResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_MyturnResp.Unmarshal(m, b)
}
func (m *Player_MyturnResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_MyturnResp.Marshal(b, m, deterministic)
}
func (dst *Player_MyturnResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_MyturnResp.Merge(dst, src)
}
func (m *Player_MyturnResp) XXX_Size() int {
	return xxx_messageInfo_Player_MyturnResp.Size(m)
}
func (m *Player_MyturnResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_MyturnResp.DiscardUnknown(m)
}

var xxx_messageInfo_Player_MyturnResp proto.InternalMessageInfo

func (m *Player_MyturnResp) GetMyturn() []*PlayerGameUnderway {
	if m != nil {
		return m.Myturn
	}
	return nil
}

// 14,15  请求获得对战的history
type Player_MyHistoryReq struct {
	// 注意，这里是player的id，使用player的id来获取这个人曾经参加过的比赛信息
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player_MyHistoryReq) Reset()         { *m = Player_MyHistoryReq{} }
func (m *Player_MyHistoryReq) String() string { return proto.CompactTextString(m) }
func (*Player_MyHistoryReq) ProtoMessage()    {}
func (*Player_MyHistoryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 12}
}
func (m *Player_MyHistoryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_MyHistoryReq.Unmarshal(m, b)
}
func (m *Player_MyHistoryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_MyHistoryReq.Marshal(b, m, deterministic)
}
func (dst *Player_MyHistoryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_MyHistoryReq.Merge(dst, src)
}
func (m *Player_MyHistoryReq) XXX_Size() int {
	return xxx_messageInfo_Player_MyHistoryReq.Size(m)
}
func (m *Player_MyHistoryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_MyHistoryReq.DiscardUnknown(m)
}

var xxx_messageInfo_Player_MyHistoryReq proto.InternalMessageInfo

func (m *Player_MyHistoryReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Player_MyHistoryResp struct {
	Myhistories          []*PlayerHistoryInfo `protobuf:"bytes,1,rep,name=myhistories,proto3" json:"myhistories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Player_MyHistoryResp) Reset()         { *m = Player_MyHistoryResp{} }
func (m *Player_MyHistoryResp) String() string { return proto.CompactTextString(m) }
func (*Player_MyHistoryResp) ProtoMessage()    {}
func (*Player_MyHistoryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 13}
}
func (m *Player_MyHistoryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_MyHistoryResp.Unmarshal(m, b)
}
func (m *Player_MyHistoryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_MyHistoryResp.Marshal(b, m, deterministic)
}
func (dst *Player_MyHistoryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_MyHistoryResp.Merge(dst, src)
}
func (m *Player_MyHistoryResp) XXX_Size() int {
	return xxx_messageInfo_Player_MyHistoryResp.Size(m)
}
func (m *Player_MyHistoryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_MyHistoryResp.DiscardUnknown(m)
}

var xxx_messageInfo_Player_MyHistoryResp proto.InternalMessageInfo

func (m *Player_MyHistoryResp) GetMyhistories() []*PlayerHistoryInfo {
	if m != nil {
		return m.Myhistories
	}
	return nil
}

// 16,17     请求收藏的history
type Player_MyCollectedHistoryReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player_MyCollectedHistoryReq) Reset()         { *m = Player_MyCollectedHistoryReq{} }
func (m *Player_MyCollectedHistoryReq) String() string { return proto.CompactTextString(m) }
func (*Player_MyCollectedHistoryReq) ProtoMessage()    {}
func (*Player_MyCollectedHistoryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 14}
}
func (m *Player_MyCollectedHistoryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_MyCollectedHistoryReq.Unmarshal(m, b)
}
func (m *Player_MyCollectedHistoryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_MyCollectedHistoryReq.Marshal(b, m, deterministic)
}
func (dst *Player_MyCollectedHistoryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_MyCollectedHistoryReq.Merge(dst, src)
}
func (m *Player_MyCollectedHistoryReq) XXX_Size() int {
	return xxx_messageInfo_Player_MyCollectedHistoryReq.Size(m)
}
func (m *Player_MyCollectedHistoryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_MyCollectedHistoryReq.DiscardUnknown(m)
}

var xxx_messageInfo_Player_MyCollectedHistoryReq proto.InternalMessageInfo

func (m *Player_MyCollectedHistoryReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Player_MyCollectedHistoryResp struct {
	// 这里也是player的id，获取这个人曾经收藏的比赛信息
	Collectedhistories   []*PlayerHistoryInfo `protobuf:"bytes,1,rep,name=collectedhistories,proto3" json:"collectedhistories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Player_MyCollectedHistoryResp) Reset()         { *m = Player_MyCollectedHistoryResp{} }
func (m *Player_MyCollectedHistoryResp) String() string { return proto.CompactTextString(m) }
func (*Player_MyCollectedHistoryResp) ProtoMessage()    {}
func (*Player_MyCollectedHistoryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 15}
}
func (m *Player_MyCollectedHistoryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_MyCollectedHistoryResp.Unmarshal(m, b)
}
func (m *Player_MyCollectedHistoryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_MyCollectedHistoryResp.Marshal(b, m, deterministic)
}
func (dst *Player_MyCollectedHistoryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_MyCollectedHistoryResp.Merge(dst, src)
}
func (m *Player_MyCollectedHistoryResp) XXX_Size() int {
	return xxx_messageInfo_Player_MyCollectedHistoryResp.Size(m)
}
func (m *Player_MyCollectedHistoryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_MyCollectedHistoryResp.DiscardUnknown(m)
}

var xxx_messageInfo_Player_MyCollectedHistoryResp proto.InternalMessageInfo

func (m *Player_MyCollectedHistoryResp) GetCollectedhistories() []*PlayerHistoryInfo {
	if m != nil {
		return m.Collectedhistories
	}
	return nil
}

// 18 19 请求获得头像
type Player_AvatarReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player_AvatarReq) Reset()         { *m = Player_AvatarReq{} }
func (m *Player_AvatarReq) String() string { return proto.CompactTextString(m) }
func (*Player_AvatarReq) ProtoMessage()    {}
func (*Player_AvatarReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 16}
}
func (m *Player_AvatarReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_AvatarReq.Unmarshal(m, b)
}
func (m *Player_AvatarReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_AvatarReq.Marshal(b, m, deterministic)
}
func (dst *Player_AvatarReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_AvatarReq.Merge(dst, src)
}
func (m *Player_AvatarReq) XXX_Size() int {
	return xxx_messageInfo_Player_AvatarReq.Size(m)
}
func (m *Player_AvatarReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_AvatarReq.DiscardUnknown(m)
}

var xxx_messageInfo_Player_AvatarReq proto.InternalMessageInfo

func (m *Player_AvatarReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Player_AvatarResp struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player_AvatarResp) Reset()         { *m = Player_AvatarResp{} }
func (m *Player_AvatarResp) String() string { return proto.CompactTextString(m) }
func (*Player_AvatarResp) ProtoMessage()    {}
func (*Player_AvatarResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 17}
}
func (m *Player_AvatarResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player_AvatarResp.Unmarshal(m, b)
}
func (m *Player_AvatarResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player_AvatarResp.Marshal(b, m, deterministic)
}
func (dst *Player_AvatarResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player_AvatarResp.Merge(dst, src)
}
func (m *Player_AvatarResp) XXX_Size() int {
	return xxx_messageInfo_Player_AvatarResp.Size(m)
}
func (m *Player_AvatarResp) XXX_DiscardUnknown() {
	xxx_messageInfo_Player_AvatarResp.DiscardUnknown(m)
}

var xxx_messageInfo_Player_AvatarResp proto.InternalMessageInfo

func (m *Player_AvatarResp) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// 进行中的棋局
type PlayerGameUnderway struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OpponentStatus       bool     `protobuf:"varint,2,opt,name=opponent_status,json=opponentStatus,proto3" json:"opponent_status,omitempty"`
	OpponentId           int64    `protobuf:"varint,3,opt,name=opponent_id,json=opponentId,proto3" json:"opponent_id,omitempty"`
	OpponentNickname     string   `protobuf:"bytes,4,opt,name=opponent_nickname,json=opponentNickname,proto3" json:"opponent_nickname,omitempty"`
	OpponentProfile      string   `protobuf:"bytes,5,opt,name=opponent_profile,json=opponentProfile,proto3" json:"opponent_profile,omitempty"`
	Bystanders           int64    `protobuf:"varint,6,opt,name=bystanders,proto3" json:"bystanders,omitempty"`
	Step                 int64    `protobuf:"varint,7,opt,name=step,proto3" json:"step,omitempty"`
	Likenum              int64    `protobuf:"varint,8,opt,name=likenum,proto3" json:"likenum,omitempty"`
	Laststeptime         string   `protobuf:"bytes,9,opt,name=laststeptime,proto3" json:"laststeptime,omitempty"`
	Type                 int64    `protobuf:"varint,10,opt,name=type,proto3" json:"type,omitempty"`
	Commentnum           int64    `protobuf:"varint,11,opt,name=commentnum,proto3" json:"commentnum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerGameUnderway) Reset()         { *m = PlayerGameUnderway{} }
func (m *PlayerGameUnderway) String() string { return proto.CompactTextString(m) }
func (*PlayerGameUnderway) ProtoMessage()    {}
func (*PlayerGameUnderway) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 18}
}
func (m *PlayerGameUnderway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerGameUnderway.Unmarshal(m, b)
}
func (m *PlayerGameUnderway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerGameUnderway.Marshal(b, m, deterministic)
}
func (dst *PlayerGameUnderway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerGameUnderway.Merge(dst, src)
}
func (m *PlayerGameUnderway) XXX_Size() int {
	return xxx_messageInfo_PlayerGameUnderway.Size(m)
}
func (m *PlayerGameUnderway) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerGameUnderway.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerGameUnderway proto.InternalMessageInfo

func (m *PlayerGameUnderway) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerGameUnderway) GetOpponentStatus() bool {
	if m != nil {
		return m.OpponentStatus
	}
	return false
}

func (m *PlayerGameUnderway) GetOpponentId() int64 {
	if m != nil {
		return m.OpponentId
	}
	return 0
}

func (m *PlayerGameUnderway) GetOpponentNickname() string {
	if m != nil {
		return m.OpponentNickname
	}
	return ""
}

func (m *PlayerGameUnderway) GetOpponentProfile() string {
	if m != nil {
		return m.OpponentProfile
	}
	return ""
}

func (m *PlayerGameUnderway) GetBystanders() int64 {
	if m != nil {
		return m.Bystanders
	}
	return 0
}

func (m *PlayerGameUnderway) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *PlayerGameUnderway) GetLikenum() int64 {
	if m != nil {
		return m.Likenum
	}
	return 0
}

func (m *PlayerGameUnderway) GetLaststeptime() string {
	if m != nil {
		return m.Laststeptime
	}
	return ""
}

func (m *PlayerGameUnderway) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PlayerGameUnderway) GetCommentnum() int64 {
	if m != nil {
		return m.Commentnum
	}
	return 0
}

// 别人的邀请
type PlayerPending struct {
	OpponentStatus       bool     `protobuf:"varint,1,opt,name=opponent_status,json=opponentStatus,proto3" json:"opponent_status,omitempty"`
	OpponentId           int64    `protobuf:"varint,2,opt,name=opponent_id,json=opponentId,proto3" json:"opponent_id,omitempty"`
	OpponentNickname     string   `protobuf:"bytes,3,opt,name=opponent_nickname,json=opponentNickname,proto3" json:"opponent_nickname,omitempty"`
	OpponentProfile      string   `protobuf:"bytes,4,opt,name=opponent_profile,json=opponentProfile,proto3" json:"opponent_profile,omitempty"`
	OpponentDan          int64    `protobuf:"varint,5,opt,name=opponent_dan,json=opponentDan,proto3" json:"opponent_dan,omitempty"`
	Boardsize            int64    `protobuf:"varint,6,opt,name=boardsize,proto3" json:"boardsize,omitempty"`
	Color                bool     `protobuf:"varint,7,opt,name=color,proto3" json:"color,omitempty"`
	Time                 string   `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	Type                 string   `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerPending) Reset()         { *m = PlayerPending{} }
func (m *PlayerPending) String() string { return proto.CompactTextString(m) }
func (*PlayerPending) ProtoMessage()    {}
func (*PlayerPending) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 19}
}
func (m *PlayerPending) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerPending.Unmarshal(m, b)
}
func (m *PlayerPending) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerPending.Marshal(b, m, deterministic)
}
func (dst *PlayerPending) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerPending.Merge(dst, src)
}
func (m *PlayerPending) XXX_Size() int {
	return xxx_messageInfo_PlayerPending.Size(m)
}
func (m *PlayerPending) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerPending.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerPending proto.InternalMessageInfo

func (m *PlayerPending) GetOpponentStatus() bool {
	if m != nil {
		return m.OpponentStatus
	}
	return false
}

func (m *PlayerPending) GetOpponentId() int64 {
	if m != nil {
		return m.OpponentId
	}
	return 0
}

func (m *PlayerPending) GetOpponentNickname() string {
	if m != nil {
		return m.OpponentNickname
	}
	return ""
}

func (m *PlayerPending) GetOpponentProfile() string {
	if m != nil {
		return m.OpponentProfile
	}
	return ""
}

func (m *PlayerPending) GetOpponentDan() int64 {
	if m != nil {
		return m.OpponentDan
	}
	return 0
}

func (m *PlayerPending) GetBoardsize() int64 {
	if m != nil {
		return m.Boardsize
	}
	return 0
}

func (m *PlayerPending) GetColor() bool {
	if m != nil {
		return m.Color
	}
	return false
}

func (m *PlayerPending) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *PlayerPending) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// 历史棋局信息
type PlayerHistoryInfo struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// player相关信息
	Player1Id       int64  `protobuf:"varint,2,opt,name=player1_id,json=player1Id,proto3" json:"player1_id,omitempty"`
	Player1Nickname string `protobuf:"bytes,3,opt,name=player1_nickname,json=player1Nickname,proto3" json:"player1_nickname,omitempty"`
	Player1Profile  string `protobuf:"bytes,4,opt,name=player1_profile,json=player1Profile,proto3" json:"player1_profile,omitempty"`
	Player1Score    int64  `protobuf:"varint,5,opt,name=player1_score,json=player1Score,proto3" json:"player1_score,omitempty"`
	Player2Id       int64  `protobuf:"varint,6,opt,name=player2_id,json=player2Id,proto3" json:"player2_id,omitempty"`
	Player2Nickname string `protobuf:"bytes,7,opt,name=player2_nickname,json=player2Nickname,proto3" json:"player2_nickname,omitempty"`
	Player2Profile  string `protobuf:"bytes,8,opt,name=player2_profile,json=player2Profile,proto3" json:"player2_profile,omitempty"`
	Player2Score    int64  `protobuf:"varint,9,opt,name=player2_score,json=player2Score,proto3" json:"player2_score,omitempty"`
	// 数字信息
	Bystanders int64 `protobuf:"varint,10,opt,name=bystanders,proto3" json:"bystanders,omitempty"`
	Step       int64 `protobuf:"varint,11,opt,name=step,proto3" json:"step,omitempty"`
	Likenum    int64 `protobuf:"varint,12,opt,name=likenum,proto3" json:"likenum,omitempty"`
	Type       int64 `protobuf:"varint,13,opt,name=type,proto3" json:"type,omitempty"`
	Commentnum int64 `protobuf:"varint,14,opt,name=commentnum,proto3" json:"commentnum,omitempty"`
	Winner     int64 `protobuf:"varint,15,opt,name=winner,proto3" json:"winner,omitempty"`
	// 字符串信息
	Finishtime           string   `protobuf:"bytes,16,opt,name=finishtime,proto3" json:"finishtime,omitempty"`
	Board                string   `protobuf:"bytes,17,opt,name=board,proto3" json:"board,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerHistoryInfo) Reset()         { *m = PlayerHistoryInfo{} }
func (m *PlayerHistoryInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerHistoryInfo) ProtoMessage()    {}
func (*PlayerHistoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{0, 20}
}
func (m *PlayerHistoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerHistoryInfo.Unmarshal(m, b)
}
func (m *PlayerHistoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerHistoryInfo.Marshal(b, m, deterministic)
}
func (dst *PlayerHistoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerHistoryInfo.Merge(dst, src)
}
func (m *PlayerHistoryInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerHistoryInfo.Size(m)
}
func (m *PlayerHistoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerHistoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerHistoryInfo proto.InternalMessageInfo

func (m *PlayerHistoryInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlayerHistoryInfo) GetPlayer1Id() int64 {
	if m != nil {
		return m.Player1Id
	}
	return 0
}

func (m *PlayerHistoryInfo) GetPlayer1Nickname() string {
	if m != nil {
		return m.Player1Nickname
	}
	return ""
}

func (m *PlayerHistoryInfo) GetPlayer1Profile() string {
	if m != nil {
		return m.Player1Profile
	}
	return ""
}

func (m *PlayerHistoryInfo) GetPlayer1Score() int64 {
	if m != nil {
		return m.Player1Score
	}
	return 0
}

func (m *PlayerHistoryInfo) GetPlayer2Id() int64 {
	if m != nil {
		return m.Player2Id
	}
	return 0
}

func (m *PlayerHistoryInfo) GetPlayer2Nickname() string {
	if m != nil {
		return m.Player2Nickname
	}
	return ""
}

func (m *PlayerHistoryInfo) GetPlayer2Profile() string {
	if m != nil {
		return m.Player2Profile
	}
	return ""
}

func (m *PlayerHistoryInfo) GetPlayer2Score() int64 {
	if m != nil {
		return m.Player2Score
	}
	return 0
}

func (m *PlayerHistoryInfo) GetBystanders() int64 {
	if m != nil {
		return m.Bystanders
	}
	return 0
}

func (m *PlayerHistoryInfo) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *PlayerHistoryInfo) GetLikenum() int64 {
	if m != nil {
		return m.Likenum
	}
	return 0
}

func (m *PlayerHistoryInfo) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PlayerHistoryInfo) GetCommentnum() int64 {
	if m != nil {
		return m.Commentnum
	}
	return 0
}

func (m *PlayerHistoryInfo) GetWinner() int64 {
	if m != nil {
		return m.Winner
	}
	return 0
}

func (m *PlayerHistoryInfo) GetFinishtime() string {
	if m != nil {
		return m.Finishtime
	}
	return ""
}

func (m *PlayerHistoryInfo) GetBoard() string {
	if m != nil {
		return m.Board
	}
	return ""
}

type Ai struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ai) Reset()         { *m = Ai{} }
func (m *Ai) String() string { return proto.CompactTextString(m) }
func (*Ai) ProtoMessage()    {}
func (*Ai) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{1}
}
func (m *Ai) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ai.Unmarshal(m, b)
}
func (m *Ai) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ai.Marshal(b, m, deterministic)
}
func (dst *Ai) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ai.Merge(dst, src)
}
func (m *Ai) XXX_Size() int {
	return xxx_messageInfo_Ai.Size(m)
}
func (m *Ai) XXX_DiscardUnknown() {
	xxx_messageInfo_Ai.DiscardUnknown(m)
}

var xxx_messageInfo_Ai proto.InternalMessageInfo

// 棋的坐标
type Ai_Position struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ai_Position) Reset()         { *m = Ai_Position{} }
func (m *Ai_Position) String() string { return proto.CompactTextString(m) }
func (*Ai_Position) ProtoMessage()    {}
func (*Ai_Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{1, 0}
}
func (m *Ai_Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ai_Position.Unmarshal(m, b)
}
func (m *Ai_Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ai_Position.Marshal(b, m, deterministic)
}
func (dst *Ai_Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ai_Position.Merge(dst, src)
}
func (m *Ai_Position) XXX_Size() int {
	return xxx_messageInfo_Ai_Position.Size(m)
}
func (m *Ai_Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Ai_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Ai_Position proto.InternalMessageInfo

func (m *Ai_Position) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Ai_Position) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Ai_Ainewgamereq struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Flag                 bool         `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
	Color                bool         `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"`
	Size                 string       `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Position             *Ai_Position `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Ai_Ainewgamereq) Reset()         { *m = Ai_Ainewgamereq{} }
func (m *Ai_Ainewgamereq) String() string { return proto.CompactTextString(m) }
func (*Ai_Ainewgamereq) ProtoMessage()    {}
func (*Ai_Ainewgamereq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{1, 1}
}
func (m *Ai_Ainewgamereq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ai_Ainewgamereq.Unmarshal(m, b)
}
func (m *Ai_Ainewgamereq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ai_Ainewgamereq.Marshal(b, m, deterministic)
}
func (dst *Ai_Ainewgamereq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ai_Ainewgamereq.Merge(dst, src)
}
func (m *Ai_Ainewgamereq) XXX_Size() int {
	return xxx_messageInfo_Ai_Ainewgamereq.Size(m)
}
func (m *Ai_Ainewgamereq) XXX_DiscardUnknown() {
	xxx_messageInfo_Ai_Ainewgamereq.DiscardUnknown(m)
}

var xxx_messageInfo_Ai_Ainewgamereq proto.InternalMessageInfo

func (m *Ai_Ainewgamereq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Ai_Ainewgamereq) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}

func (m *Ai_Ainewgamereq) GetColor() bool {
	if m != nil {
		return m.Color
	}
	return false
}

func (m *Ai_Ainewgamereq) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Ai_Ainewgamereq) GetPosition() *Ai_Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type Ai_Playerstep struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position             *Ai_Position `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Ai_Playerstep) Reset()         { *m = Ai_Playerstep{} }
func (m *Ai_Playerstep) String() string { return proto.CompactTextString(m) }
func (*Ai_Playerstep) ProtoMessage()    {}
func (*Ai_Playerstep) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{1, 2}
}
func (m *Ai_Playerstep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ai_Playerstep.Unmarshal(m, b)
}
func (m *Ai_Playerstep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ai_Playerstep.Marshal(b, m, deterministic)
}
func (dst *Ai_Playerstep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ai_Playerstep.Merge(dst, src)
}
func (m *Ai_Playerstep) XXX_Size() int {
	return xxx_messageInfo_Ai_Playerstep.Size(m)
}
func (m *Ai_Playerstep) XXX_DiscardUnknown() {
	xxx_messageInfo_Ai_Playerstep.DiscardUnknown(m)
}

var xxx_messageInfo_Ai_Playerstep proto.InternalMessageInfo

func (m *Ai_Playerstep) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Ai_Playerstep) GetPosition() *Ai_Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type Ai_Aistep struct {
	Position             *Ai_Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Ai_Aistep) Reset()         { *m = Ai_Aistep{} }
func (m *Ai_Aistep) String() string { return proto.CompactTextString(m) }
func (*Ai_Aistep) ProtoMessage()    {}
func (*Ai_Aistep) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{1, 3}
}
func (m *Ai_Aistep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ai_Aistep.Unmarshal(m, b)
}
func (m *Ai_Aistep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ai_Aistep.Marshal(b, m, deterministic)
}
func (dst *Ai_Aistep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ai_Aistep.Merge(dst, src)
}
func (m *Ai_Aistep) XXX_Size() int {
	return xxx_messageInfo_Ai_Aistep.Size(m)
}
func (m *Ai_Aistep) XXX_DiscardUnknown() {
	xxx_messageInfo_Ai_Aistep.DiscardUnknown(m)
}

var xxx_messageInfo_Ai_Aistep proto.InternalMessageInfo

func (m *Ai_Aistep) GetPosition() *Ai_Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type Ai_Aioldgameresp struct {
	Chessboard           string   `protobuf:"bytes,1,opt,name=chessboard,proto3" json:"chessboard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ai_Aioldgameresp) Reset()         { *m = Ai_Aioldgameresp{} }
func (m *Ai_Aioldgameresp) String() string { return proto.CompactTextString(m) }
func (*Ai_Aioldgameresp) ProtoMessage()    {}
func (*Ai_Aioldgameresp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_0ed7e08f59e1174e, []int{1, 4}
}
func (m *Ai_Aioldgameresp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ai_Aioldgameresp.Unmarshal(m, b)
}
func (m *Ai_Aioldgameresp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ai_Aioldgameresp.Marshal(b, m, deterministic)
}
func (dst *Ai_Aioldgameresp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ai_Aioldgameresp.Merge(dst, src)
}
func (m *Ai_Aioldgameresp) XXX_Size() int {
	return xxx_messageInfo_Ai_Aioldgameresp.Size(m)
}
func (m *Ai_Aioldgameresp) XXX_DiscardUnknown() {
	xxx_messageInfo_Ai_Aioldgameresp.DiscardUnknown(m)
}

var xxx_messageInfo_Ai_Aioldgameresp proto.InternalMessageInfo

func (m *Ai_Aioldgameresp) GetChessboard() string {
	if m != nil {
		return m.Chessboard
	}
	return ""
}

func init() {
	proto.RegisterType((*Player)(nil), "Module.Player")
	proto.RegisterType((*Player_LoginReq)(nil), "Module.Player.LoginReq")
	proto.RegisterType((*Player_LoginResp)(nil), "Module.Player.LoginResp")
	proto.RegisterType((*Player_RegisterReq)(nil), "Module.Player.RegisterReq")
	proto.RegisterType((*Player_RegisterResp)(nil), "Module.Player.RegisterResp")
	proto.RegisterType((*Player_PlayerInfoReq)(nil), "Module.Player.PlayerInfoReq")
	proto.RegisterType((*Player_PlayerInfoResp)(nil), "Module.Player.PlayerInfoResp")
	proto.RegisterType((*Player_TheirturnReq)(nil), "Module.Player.TheirturnReq")
	proto.RegisterType((*Player_TheirturnResp)(nil), "Module.Player.TheirturnResp")
	proto.RegisterType((*Player_PendingReq)(nil), "Module.Player.PendingReq")
	proto.RegisterType((*Player_PendingResp)(nil), "Module.Player.PendingResp")
	proto.RegisterType((*Player_MyturnReq)(nil), "Module.Player.MyturnReq")
	proto.RegisterType((*Player_MyturnResp)(nil), "Module.Player.MyturnResp")
	proto.RegisterType((*Player_MyHistoryReq)(nil), "Module.Player.MyHistoryReq")
	proto.RegisterType((*Player_MyHistoryResp)(nil), "Module.Player.MyHistoryResp")
	proto.RegisterType((*Player_MyCollectedHistoryReq)(nil), "Module.Player.MyCollectedHistoryReq")
	proto.RegisterType((*Player_MyCollectedHistoryResp)(nil), "Module.Player.MyCollectedHistoryResp")
	proto.RegisterType((*Player_AvatarReq)(nil), "Module.Player.AvatarReq")
	proto.RegisterType((*Player_AvatarResp)(nil), "Module.Player.AvatarResp")
	proto.RegisterType((*PlayerGameUnderway)(nil), "Module.Player.game_underway")
	proto.RegisterType((*PlayerPending)(nil), "Module.Player.pending")
	proto.RegisterType((*PlayerHistoryInfo)(nil), "Module.Player.history_info")
	proto.RegisterType((*Ai)(nil), "Module.Ai")
	proto.RegisterType((*Ai_Position)(nil), "Module.Ai.Position")
	proto.RegisterType((*Ai_Ainewgamereq)(nil), "Module.Ai.Ainewgamereq")
	proto.RegisterType((*Ai_Playerstep)(nil), "Module.Ai.Playerstep")
	proto.RegisterType((*Ai_Aistep)(nil), "Module.Ai.Aistep")
	proto.RegisterType((*Ai_Aioldgameresp)(nil), "Module.Ai.Aioldgameresp")
	proto.RegisterEnum("Module.ModuleId", ModuleId_name, ModuleId_value)
	proto.RegisterEnum("Module.Player_LoginResp_LoginResult", Player_LoginResp_LoginResult_name, Player_LoginResp_LoginResult_value)
	proto.RegisterEnum("Module.Player_RegisterResp_RegisterResult", Player_RegisterResp_RegisterResult_name, Player_RegisterResp_RegisterResult_value)
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_protocol_0ed7e08f59e1174e) }

var fileDescriptor_protocol_0ed7e08f59e1174e = []byte{
	// 1218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xdf, 0x6e, 0xe4, 0xb4,
	0x17, 0xde, 0xcc, 0x4c, 0xa7, 0x33, 0x67, 0xfe, 0xd4, 0xf5, 0x76, 0xfb, 0xcb, 0x2f, 0x5b, 0xba,
	0xa5, 0x20, 0xba, 0x2c, 0x52, 0x17, 0x06, 0x6e, 0x40, 0x20, 0x34, 0x65, 0x41, 0x54, 0x4b, 0x4b,
	0x95, 0xae, 0xb4, 0x97, 0x55, 0x9a, 0xb8, 0x53, 0x6b, 0x33, 0x76, 0x88, 0x13, 0xda, 0xf0, 0x0e,
	0xdc, 0xf0, 0x00, 0x5c, 0x23, 0x9e, 0x80, 0xa7, 0xe0, 0x35, 0x78, 0x04, 0x6e, 0x91, 0xed, 0x38,
	0x71, 0xa6, 0x53, 0xd4, 0x8a, 0x3b, 0x9f, 0xef, 0x1c, 0xfb, 0x7c, 0xfe, 0x7c, 0x1c, 0x9f, 0xc0,
	0x38, 0x49, 0x79, 0xc6, 0x43, 0x1e, 0xef, 0xab, 0x01, 0xee, 0x1e, 0xf1, 0x28, 0x8f, 0xc9, 0xee,
	0x1f, 0x0f, 0xa1, 0x7b, 0x12, 0x07, 0x05, 0x49, 0xbd, 0x03, 0xe8, 0x7d, 0xc7, 0x67, 0x94, 0xf9,
	0xe4, 0x07, 0xec, 0x41, 0x2f, 0x17, 0x24, 0x3d, 0x0e, 0xe6, 0xc4, 0x75, 0x76, 0x9c, 0xa7, 0x7d,
	0xbf, 0xb2, 0xa5, 0x2f, 0x09, 0x84, 0x78, 0xcd, 0xd3, 0xc8, 0x6d, 0x69, 0x9f, 0xb1, 0xbd, 0x3f,
	0x1d, 0xe8, 0x97, 0x8b, 0x88, 0x04, 0x7f, 0x0e, 0xdd, 0x94, 0x88, 0x3c, 0xce, 0xd4, 0x1a, 0xe3,
	0xc9, 0xbb, 0xfb, 0x3a, 0xeb, 0xbe, 0xce, 0xb8, 0x5f, 0x45, 0x56, 0xa3, 0x3c, 0xce, 0xfc, 0x72,
	0x0e, 0x1e, 0x43, 0x8b, 0x9a, 0x0c, 0x2d, 0x1a, 0xed, 0x0a, 0x18, 0x58, 0x61, 0x78, 0x1d, 0x46,
	0xca, 0x3c, 0x3b, 0xcd, 0xc3, 0x90, 0x08, 0x81, 0x1e, 0xd4, 0xd0, 0x37, 0x01, 0x8d, 0xf3, 0x94,
	0x20, 0x07, 0xef, 0xc0, 0x96, 0x86, 0x5e, 0xa7, 0x9c, 0xcd, 0x4e, 0x02, 0x21, 0xae, 0x78, 0x1a,
	0x7d, 0x9f, 0x4e, 0xc3, 0x90, 0xe7, 0x2c, 0x43, 0x2d, 0xbc, 0x05, 0xae, 0x8e, 0x38, 0xe6, 0x8c,
	0x5c, 0x53, 0x91, 0x11, 0x96, 0x19, 0x6f, 0xdb, 0xfb, 0x1a, 0x06, 0x3e, 0x99, 0x49, 0x34, 0xfd,
	0x2f, 0xba, 0xfc, 0xe6, 0xc0, 0xb0, 0x5e, 0x47, 0x24, 0xf8, 0x60, 0x41, 0x9a, 0x67, 0x0b, 0xd2,
	0xd8, 0xc1, 0xb6, 0x61, 0x09, 0xb4, 0xfb, 0x0a, 0xc6, 0x4d, 0x0f, 0xde, 0x00, 0x64, 0x10, 0x4b,
	0x16, 0x1b, 0xad, 0x95, 0xd9, 0x04, 0x5c, 0xa1, 0x2f, 0xf2, 0x24, 0xa6, 0x61, 0x90, 0x11, 0xd4,
	0xf2, 0x9e, 0xc0, 0x48, 0x73, 0x38, 0x64, 0x17, 0x5c, 0xee, 0x59, 0x9f, 0x83, 0x63, 0xce, 0xc1,
	0x8b, 0x60, 0x6c, 0x07, 0x88, 0x44, 0xee, 0x9c, 0xd1, 0xf0, 0x0d, 0xb3, 0x54, 0x31, 0x36, 0xde,
	0x84, 0x6e, 0xf0, 0x63, 0x90, 0x05, 0x69, 0xa9, 0x49, 0x69, 0xe1, 0x6d, 0x00, 0x3d, 0x22, 0xd1,
	0x8c, 0xb8, 0x6d, 0xe5, 0xb3, 0x10, 0x6f, 0x1b, 0x86, 0xaf, 0x2e, 0x09, 0x4d, 0xb3, 0x3c, 0x65,
	0xcb, 0x58, 0xbc, 0x84, 0x91, 0xe5, 0x17, 0x09, 0xfe, 0x0c, 0xfa, 0x99, 0x01, 0x5c, 0x67, 0xa7,
	0xfd, 0x74, 0x30, 0xd9, 0x5a, 0x10, 0x75, 0x16, 0xcc, 0xc9, 0x59, 0xce, 0x22, 0x92, 0x5e, 0x05,
	0x85, 0x5f, 0x87, 0x7b, 0x5b, 0x00, 0x27, 0x84, 0x45, 0x94, 0xcd, 0x96, 0xa5, 0xfa, 0x12, 0x06,
	0x95, 0x57, 0x24, 0xf8, 0x43, 0x58, 0x4d, 0xb4, 0x59, 0xa6, 0xd9, 0x5c, 0x48, 0x53, 0x7a, 0x7d,
	0x13, 0xe6, 0x3d, 0x86, 0xfe, 0x51, 0x71, 0xdb, 0x46, 0x0e, 0x00, 0x8c, 0x53, 0x24, 0xf8, 0x13,
	0xe8, 0xce, 0x8b, 0x3b, 0x6f, 0xa1, 0x8c, 0x95, 0x62, 0x1d, 0x15, 0xdf, 0x52, 0x91, 0xf1, 0xb4,
	0x58, 0x96, 0xe3, 0x18, 0x46, 0x96, 0x5f, 0x24, 0xf8, 0x0b, 0x18, 0xcc, 0x8b, 0x4b, 0x05, 0x50,
	0x22, 0xca, 0x5c, 0x8f, 0x17, 0x72, 0x69, 0x7f, 0x71, 0x46, 0xe5, 0x39, 0xdb, 0xf1, 0xde, 0x1e,
	0x3c, 0x3a, 0x2a, 0xbe, 0xe2, 0x71, 0x4c, 0xc2, 0x8c, 0x44, 0xff, 0x92, 0x98, 0xc0, 0xe6, 0xb2,
	0x40, 0x91, 0xe0, 0x97, 0x80, 0x43, 0x83, 0xdf, 0x8b, 0xc8, 0x92, 0x69, 0x52, 0xe0, 0xa9, 0x2a,
	0x9d, 0x65, 0x1c, 0xb6, 0x01, 0x8c, 0x53, 0x24, 0x18, 0x41, 0x3b, 0x4f, 0xe3, 0xd2, 0x2d, 0x87,
	0xde, 0x5f, 0x2d, 0x18, 0x35, 0x64, 0xb5, 0x56, 0x68, 0xcb, 0x15, 0xf0, 0x1e, 0xac, 0xf1, 0x24,
	0xe1, 0x8c, 0xb0, 0xec, 0x4c, 0x64, 0x41, 0x96, 0x0b, 0x55, 0xcc, 0x3d, 0x7f, 0x6c, 0xe0, 0x53,
	0x85, 0xe2, 0x27, 0x30, 0xa8, 0x02, 0x69, 0xa4, 0xaa, 0xba, 0xed, 0x83, 0x81, 0x0e, 0x23, 0xfc,
	0x01, 0xac, 0x57, 0x01, 0xd5, 0x95, 0xe9, 0x28, 0x2e, 0xc8, 0x38, 0x8e, 0xcd, 0xd5, 0x79, 0x1f,
	0x2a, 0xec, 0x2c, 0x49, 0xf9, 0x05, 0x8d, 0x89, 0xbb, 0xa2, 0x62, 0x2b, 0x3a, 0x27, 0x1a, 0x96,
	0xb7, 0xe9, 0xbc, 0x10, 0x59, 0x20, 0x77, 0x20, 0xdc, 0xae, 0xce, 0x5b, 0x23, 0x18, 0x43, 0x47,
	0x64, 0x24, 0x71, 0x57, 0x95, 0x47, 0x8d, 0xb1, 0x0b, 0xab, 0x31, 0x7d, 0x43, 0x58, 0x3e, 0x77,
	0x7b, 0x0a, 0x36, 0x26, 0xde, 0x85, 0x61, 0x1c, 0x88, 0x4c, 0x46, 0x65, 0x74, 0x4e, 0xdc, 0xbe,
	0x4a, 0xda, 0xc0, 0xe4, 0x8a, 0x59, 0x91, 0x10, 0x17, 0xf4, 0x8a, 0x72, 0x2c, 0x59, 0x84, 0x7c,
	0x3e, 0x27, 0x2c, 0x93, 0x8b, 0x0e, 0x34, 0x8b, 0x1a, 0xf1, 0x7e, 0x6f, 0x55, 0x57, 0x67, 0x99,
	0xa6, 0xce, 0x5d, 0x34, 0x6d, 0xdd, 0x4d, 0xd3, 0xf6, 0x3d, 0x34, 0xed, 0x2c, 0xd7, 0xf4, 0x6d,
	0x18, 0x56, 0xa1, 0x51, 0xc0, 0x94, 0xf4, 0x6d, 0xbf, 0x22, 0xf3, 0x22, 0x60, 0x78, 0x0b, 0xfa,
	0xe7, 0x3c, 0x48, 0x23, 0x41, 0x7f, 0x22, 0xa5, 0xea, 0x35, 0x80, 0x37, 0x60, 0x25, 0xe4, 0x31,
	0x4f, 0x95, 0xea, 0x3d, 0x5f, 0x1b, 0x4a, 0x38, 0x29, 0x6a, 0x4f, 0x65, 0xed, 0x34, 0xc4, 0xec,
	0x97, 0x58, 0x91, 0x10, 0xef, 0xd7, 0x0e, 0x0c, 0xed, 0xc2, 0xbf, 0x51, 0x95, 0x6f, 0x01, 0x24,
	0xea, 0x7e, 0x7c, 0x54, 0xeb, 0xd2, 0x2f, 0x91, 0xc3, 0x48, 0xee, 0xd4, 0xb8, 0x17, 0x54, 0x59,
	0x2b, 0xf1, 0x4a, 0x94, 0x3d, 0x30, 0xd0, 0x82, 0x26, 0xe3, 0x12, 0x36, 0x92, 0xbc, 0x03, 0x23,
	0x13, 0x28, 0x42, 0x9e, 0x92, 0x52, 0x93, 0x61, 0x09, 0x9e, 0x4a, 0xac, 0xe6, 0x35, 0x91, 0xbc,
	0xba, 0x36, 0xaf, 0x89, 0xcd, 0x6b, 0x52, 0xf3, 0x5a, 0xb5, 0x79, 0x4d, 0x6e, 0xf2, 0x9a, 0x54,
	0xbc, 0x7a, 0x36, 0xaf, 0xc9, 0x0d, 0x5e, 0x93, 0x92, 0x57, 0xdf, 0xe6, 0x35, 0xd1, 0xbc, 0x9a,
	0x77, 0x04, 0x6e, 0xbd, 0x23, 0x83, 0xe5, 0x77, 0x64, 0xd8, 0xbc, 0x23, 0xe6, 0xc8, 0x46, 0xb7,
	0xd6, 0xff, 0x78, 0xb1, 0xfe, 0xe5, 0x5b, 0x78, 0x45, 0x19, 0x23, 0xa9, 0xbb, 0xa6, 0x7c, 0xa5,
	0x25, 0xe7, 0x5d, 0x50, 0x46, 0xc5, 0xa5, 0x2a, 0x0c, 0xa4, 0xdf, 0xc2, 0x1a, 0x91, 0x85, 0xa4,
	0xaa, 0xca, 0x5d, 0x57, 0x2e, 0x6d, 0xec, 0xfe, 0xdd, 0x82, 0xd6, 0x94, 0x7a, 0xef, 0x41, 0xef,
	0x84, 0x0b, 0x9a, 0x51, 0xce, 0xf0, 0x10, 0x9c, 0x6b, 0x55, 0x21, 0x2b, 0xbe, 0x73, 0x2d, 0xad,
	0x42, 0xd5, 0xc5, 0x8a, 0xef, 0x14, 0xde, 0xcf, 0x0e, 0x0c, 0xa7, 0x94, 0x91, 0x2b, 0xf9, 0xad,
	0x4b, 0x6f, 0x7e, 0x27, 0xe5, 0x8e, 0x2e, 0xe2, 0x60, 0x56, 0x7e, 0xda, 0xd4, 0xb8, 0x2e, 0xe1,
	0xf6, 0x42, 0x09, 0xab, 0x8a, 0xd7, 0x45, 0xa2, 0xc6, 0xf8, 0x39, 0xf4, 0x92, 0x92, 0x86, 0xaa,
	0x8a, 0xc1, 0xe4, 0xa1, 0xf9, 0x8a, 0x4f, 0xe9, 0xbe, 0x61, 0xe8, 0x57, 0x41, 0xde, 0x11, 0x80,
	0xfe, 0xbc, 0x2b, 0xa1, 0x17, 0xc9, 0xdc, 0x7b, 0xb9, 0x4f, 0xa1, 0x3b, 0xa5, 0x6a, 0x29, 0x7b,
	0xaa, 0x73, 0x97, 0xa9, 0xcf, 0x61, 0x34, 0xa5, 0x3c, 0x8e, 0xb4, 0x30, 0x22, 0x51, 0xe7, 0x78,
	0x49, 0x84, 0xd0, 0xa2, 0x6b, 0x52, 0x16, 0xf2, 0xec, 0x97, 0x36, 0xf4, 0xf4, 0x8a, 0x87, 0x11,
	0x1e, 0xd6, 0x6d, 0x33, 0x7a, 0x80, 0x47, 0x56, 0xff, 0x8b, 0x1c, 0xbc, 0xd6, 0x68, 0x1f, 0x51,
	0x0b, 0xa3, 0x66, 0x1f, 0x88, 0xda, 0xb2, 0x69, 0x6d, 0xf4, 0x5b, 0xa8, 0x83, 0xf1, 0x62, 0x87,
	0x85, 0x56, 0xe4, 0x44, 0xbb, 0x1f, 0x42, 0x5d, 0x39, 0xb1, 0xd1, 0x01, 0xa1, 0x55, 0x3c, 0xb6,
	0xfb, 0x18, 0xd4, 0x93, 0xe9, 0xad, 0xce, 0x05, 0xf5, 0x25, 0xbd, 0xaa, 0x13, 0x41, 0x20, 0xe3,
	0xeb, 0xde, 0x03, 0x0d, 0x64, 0x12, 0xbb, 0x8f, 0x40, 0x63, 0x99, 0xa4, 0xd1, 0x39, 0xa0, 0x35,
	0xfc, 0xff, 0x5b, 0x1e, 0x7f, 0x84, 0xb0, 0x77, 0xdb, 0x73, 0x8f, 0xd6, 0x65, 0xea, 0xea, 0x8d,
	0x46, 0x58, 0xa6, 0xae, 0x5f, 0x65, 0xf4, 0x50, 0xa6, 0xb6, 0xab, 0x13, 0x6d, 0xa8, 0xcd, 0x54,
	0x05, 0x82, 0x1e, 0x61, 0x30, 0x27, 0x8c, 0x36, 0x25, 0xad, 0xc6, 0x91, 0xa1, 0xff, 0x9d, 0x77,
	0xd5, 0x8f, 0xcd, 0xc7, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x0b, 0xc9, 0x05, 0xea, 0x0c,
	0x00, 0x00,
}
