language: go
go:
- '1.10'
before_install:
- openssl aes-256-cbc -K $encrypted_e9c3b1a3b89a_key -iv $encrypted_e9c3b1a3b89a_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: 169.254.184.27
after_success:
- ssh -tt kyriezhang@169.254.184.27 './demo_server.sh'
